import React from 'react';

const PrivacyPolicyPage: React.FC = () => {
  return (
    <div className="container mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6 text-center">Privacy Policy</h1>

      <p className="mb-4 text-sm text-center font-semibold">DISCLAIMER: Sear HOSTING IS NOT A REGISTERED COMPANY. Any and all contracts made are not enforceable by law as of the writing of this Privacy Policy, but shall be ratified upon registration.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Interpretation and Definitions</h2>

      <h3 className="text-xl font-semibold mt-4 mb-2">Interpretation</h3>
      <p className="mb-2">The words of which the initial letter is capitalized have meanings defined under the following conditions.</p>
      <p className="mb-4">The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

      <h3 className="text-xl font-semibold mt-4 mb-2">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc list-inside mb-4 space-y-2">
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Sear Hosting.</li>
        <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Website</strong> refers to Sear.host, accessible from www.Sear.host</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. For the purposes for GDPR, Personal Data means any information relating to You such as a name, an identification number, location data, online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity. For the purposes of the CCPA, Personal Data means any information that identifies, relates to, describes or is capable of being associated with, or could reasonably be linked, directly or indirectly, with You.</li>
        <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li>Do Not Track (DNT) is a concept that has been promoted by US regulatory authorities, in particular the U.S. Federal Trade Commission (FTC), for the Internet industry to develop and implement a mechanism for allowing internet users to control the tracking of their online activities across websites.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Collecting and Using Your Personal Data</h2>

      <h3 className="text-xl font-semibold mt-4 mb-2">Types of Data Collected</h3>

      <h4 className="text-lg font-semibold mt-3 mb-1">Personal Data</h4>
      <p className="mb-2">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
      <ul className="list-disc list-inside mb-4 space-y-1">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>

      <h4 className="text-lg font-semibold mt-3 mb-1">Usage Data</h4>
      <p className="mb-2">Usage Data is collected automatically when using the Service.</p>
      <p className="mb-2">Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
      <p className="mb-2">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
      <p className="mb-4">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

      <h4 className="text-lg font-semibold mt-3 mb-1">Tracking Technologies and Cookies</h4>
      <p className="mb-2">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
      <p className="mb-2">You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.</p>
      <p className="mb-2">Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close your web browser. Learn more about cookies: All About Cookies.</p>
      <p className="mb-2">We use both session and persistent Cookies for the purposes set out below:</p>
      <ul className="list-disc list-inside mb-4 space-y-2">
        <li>
          <strong>Necessary / Essential Cookies</strong><br />
          Type: Session Cookies<br />
          Administered By: Us<br />
          Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
        </li>
        <li>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong><br />
          Type: Persistent Cookies<br />
          Administered By: Us<br />
          Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
        </li>
        <li>
          <strong>Functionality Cookies</strong><br />
          Type: Persistent Cookies<br />
          Administered By: Us<br />
          Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
        </li>
      </ul>

      <h3 className="text-xl font-semibold mt-4 mb-2">Use of Your Personal Data</h3>
      <p className="mb-2">The Company may use Personal Data for the following purposes:</p>
      <ul className="list-disc list-inside mb-4 space-y-2">
        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
        <li><strong>To manage Your Account</strong>: to manage Your voluntary registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
        <li><strong>For the performance of a contract</strong>: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
        <li><strong>To contact You</strong>: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
        <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</li>
        <li><strong>To manage Your requests</strong>: To attend and manage Your requests to Us.</li>
      </ul>
       <p className="mb-2">We may share your personal information in the following situations:</p>
      <ul className="list-disc list-inside mb-4 space-y-2">
        <li><strong>With Service Providers</strong>: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, for payment processing, to contact You.</li>
        <li><strong>For Business transfers</strong>: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of our business to another company.</li>
        <li><strong>With Affiliates</strong>: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
        <li><strong>With other users</strong>: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside. If You interact with other users or register through a Third-Party Social Media Service, Your contacts on the Third-Party Social Media Service may see Your name, profile, pictures and description of Your activity. Similarly, other users will be able to view descriptions of Your activity, communicate with You and view Your profile.</li>
      </ul>

      <h3 className="text-xl font-semibold mt-4 mb-2">Retention of Your Personal Data</h3>
      <p className="mb-2">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
      <p className="mb-4">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>

      <h3 className="text-xl font-semibold mt-4 mb-2">Transfer of Your Personal Data</h3>
      <p className="mb-2">Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to Our and maintained on Our computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
      <p className="mb-2">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
      <p className="mb-2">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
      <p className="mb-4">To ensure compliance with GDPR and protect personal data transferred between the EU and non-EU countries, we have incorporated a Standard Contractual Clause (SCC) in our data processing agreements. This clause mandates that data importers outside the EU must adhere to strict data protection obligations, including safeguarding personal data against unauthorized access and breaches, and providing data subjects with enforceable rights. Additionally, the clause ensures that any further data transfers to third parties will only occur under similar safeguards. This SCC serves as a critical measure to maintain the integrity and security of personal data across international borders.</p>

      <h3 className="text-xl font-semibold mt-4 mb-2">Disclosure of Your Personal Data</h3>

      <h4 className="text-lg font-semibold mt-3 mb-1">Business Transactions</h4>
      <p className="mb-4">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

      <h4 className="text-lg font-semibold mt-3 mb-1">Law enforcement</h4>
      <p className="mb-4">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

      <h4 className="text-lg font-semibold mt-3 mb-1">Other legal requirements</h4>
      <p className="mb-2">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
      <ul className="list-disc list-inside mb-4 space-y-1">
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ul>

      <h3 className="text-xl font-semibold mt-4 mb-2">Security of Your Personal Data</h3>
      <p className="mb-4">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Detailed Information on the Processing of Your Personal Data</h2>
      <p className="mb-2">Service Providers have access to Your Personal Data only to perform their tasks on Our behalf and are obligated not to disclose or use it for any other purpose.</p>

      <h3 className="text-xl font-semibold mt-4 mb-2">Payments</h3>
      <p className="mb-2">We may provide paid products and/or services within the Service. In that case, we may use third-party services for payment processing (e.g. payment processors).</p>
      <p className="mb-2">We will not store or collect Your payment card details. That information is provided directly to Our third-party payment processors whose use of Your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
      <ul className="list-disc list-inside mb-4 space-y-2">
        <li>
          <strong>Stripe</strong><br />
          Their Privacy Policy can be viewed at <a href="https://stripe.com/us/privacy" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">https://stripe.com/us/privacy</a>
        </li>
        <li>
          <strong>PayPal</strong><br />
          Their Privacy Policy can be viewed at <a href="https://www.paypal.com/webapps/mpp/ua/privacy-full" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">https://www.paypal.com/webapps/mpp/ua/privacy-full</a>
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Changes to this Privacy Policy</h2>
      <p className="mb-2">We may update our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
      <p className="mb-2">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
      <p className="mb-2">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
      <p className="mb-4">You as a user will continue to enjoy: rights to access, rectification, erasure, data portability, etc. and You can access them via the &quot;Account&quot; page <a href="https://billing.Sear.host/profile" target="_blank" rel="noopener noreferrer" className="text-blue-500 hover:underline">https://billing.Sear.host/profile</a> to exercise these rights.</p>


      <h2 className="text-2xl font-semibold mt-6 mb-4">Contact Us</h2>
      <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:<br />
      By email: <a href="mailto:searhost@gmail.com" className="text-blue-500 hover:underline">searhost@gmail.com</a></p>
    </div>
  );
};

export default PrivacyPolicyPage; 